# Pre-commit configuration for LaunchLine Starter
# Install with: poetry run pre-commit install

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/
      - id: end-of-file-fixer
        exclude: ^frontend/
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^frontend/
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: detect-private-key
      - id: check-case-conflict

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        files: ^backend/
        args: [--config, backend/pyproject.toml]

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        files: ^backend/
        args: [--settings-path, backend/pyproject.toml]

  # Python linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        files: ^backend/
        args: [--config, backend/pyproject.toml, --fix]

  # Django-specific checks
  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: bash -c 'cd backend && python manage.py check --settings=config.settings.dev'
        language: system
        files: ^backend/.*\.py$
        pass_filenames: false

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^backend/
        args: [-c, backend/pyproject.toml]
        exclude: ^backend/tests/

  # Python typing (optional - only warn)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^backend/
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
          - types-python-dateutil
        args: [--config-file, backend/pyproject.toml]
        exclude: ^backend/(migrations/|tests/)

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: ^frontend/

  # Documentation
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        files: ^backend/src/
        args: [--convention=google, --add-ignore=D100,D104,D105,D107]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [django-check]  # Skip Django check in CI
  submodules: false