# Generated by Django 5.0.2 on 2025-09-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        default="Let's Create Something Amazing",
                        help_text="Main hero heading",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subheading",
                    models.TextField(
                        default="Ready to transform your vision into digital reality? We're here to make it happen with cutting-edge technology and innovative design.",
                        help_text="Hero subheading",
                        max_length=500,
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        default="Start Your Project",
                        help_text="Hero CTA button text",
                        max_length=100,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="LaunchLine LLC",
                        help_text="Company name",
                        max_length=100,
                    ),
                ),
                (
                    "company_description",
                    models.TextField(
                        default="We're passionate about creating digital experiences that drive results. Whether you're a startup with a bold vision or an established business ready to innovate, let's collaborate to bring your ideas to life.",
                        help_text="Company description for contact section",
                        max_length=500,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+1 (555) 123-4567",
                        help_text="Phone number",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello@launchline.com",
                        help_text="Email address",
                        max_length=254,
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        default="123 Innovation Drive",
                        help_text="Address line 1",
                        max_length=100,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        default="Tech City, TC 12345",
                        help_text="Address line 2",
                        max_length=100,
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Social media links as JSON array",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Metrics to display in hero section as JSON array",
                    ),
                ),
                (
                    "hero_background_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hero background image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open Graph image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
