# Generated by Django 5.0.2 on 2025-09-03 23:14

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_contactpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="hero_background_image",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="hero_cta_text",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="hero_heading",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="hero_subheading",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="metrics",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="social_links",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Main hero heading", max_length=255
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Optional subheading text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Call to action button text",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Call to action button URL",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Background image for the hero section",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "contact_info",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "company_name",
                                    wagtail.blocks.CharBlock(
                                        default="LaunchLine LLC",
                                        help_text="Company name",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "company_description",
                                    wagtail.blocks.TextBlock(
                                        default="We're passionate about creating digital experiences that drive results. Whether you're a startup with a bold vision or an established business ready to innovate, let's collaborate to bring your ideas to life.",
                                        help_text="Company description",
                                        max_length=500,
                                    ),
                                ),
                                (
                                    "phone",
                                    wagtail.blocks.CharBlock(
                                        default="+1 (555) 123-4567",
                                        help_text="Phone number",
                                        max_length=20,
                                    ),
                                ),
                                (
                                    "email",
                                    wagtail.blocks.EmailBlock(
                                        default="hello@launchline.com",
                                        help_text="Email address",
                                    ),
                                ),
                                (
                                    "address_line_1",
                                    wagtail.blocks.CharBlock(
                                        default="123 Innovation Drive",
                                        help_text="Address line 1",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "address_line_2",
                                    wagtail.blocks.CharBlock(
                                        default="Tech City, TC 12345",
                                        help_text="Address line 2",
                                        max_length=100,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "social_links",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="Connect With Us",
                                        help_text="Section heading",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "social_links",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "name",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Social platform name (e.g., LinkedIn, Twitter)",
                                                        max_length=50,
                                                    ),
                                                ),
                                                (
                                                    "url",
                                                    wagtail.blocks.URLBlock(
                                                        help_text="Social media profile URL"
                                                    ),
                                                ),
                                                (
                                                    "icon",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Icon name (e.g., linkedin, twitter, github)",
                                                        max_length=50,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Add social media links",
                                        max_num=10,
                                        min_num=1,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "metrics",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="Our Impact",
                                        help_text="Section heading",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "metrics",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "value",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Metric value (e.g., 150+, 98%, 24h)",
                                                        max_length=20,
                                                    ),
                                                ),
                                                (
                                                    "label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Metric label (e.g., Projects Completed)",
                                                        max_length=100,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Add 2-6 metrics",
                                        max_num=6,
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "link",
                                            "ol",
                                            "ul",
                                            "document-link",
                                            "image",
                                            "embed",
                                        ],
                                        help_text="Rich text content",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="CTA heading", max_length=255
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Supporting text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Button text", max_length=100
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.URLBlock(help_text="Button URL"),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary", "Primary"),
                                            ("secondary", "Secondary"),
                                            ("dark", "Dark"),
                                            ("light", "Light"),
                                        ],
                                        help_text="Background color theme",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Select an image"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional image caption",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("center", "Center"),
                                            ("right", "Right"),
                                        ],
                                        help_text="Image alignment",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
