# Generated by Django 5.0.2 on 2025-09-09 02:48

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_contactpage_address_line_1_and_more"),
        ("wagtailcore", "0091_remove_revision_submitted_for_moderation"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_background_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_heading",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_subheading",
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Main hero heading", max_length=255
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Optional subheading text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Call to action button text",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Call to action button URL",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Background image for the hero section",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "link",
                                            "ol",
                                            "ul",
                                            "document-link",
                                            "image",
                                            "embed",
                                        ],
                                        help_text="Rich text content",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="CTA heading", max_length=255
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Supporting text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Button text", max_length=100
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.URLBlock(help_text="Button URL"),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary", "Primary"),
                                            ("secondary", "Secondary"),
                                            ("dark", "Dark"),
                                            ("light", "Light"),
                                        ],
                                        help_text="Background color theme",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Select an image"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional image caption",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("center", "Center"),
                                            ("right", "Right"),
                                        ],
                                        help_text="Image alignment",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="Optional blog introduction (legacy field)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Main hero heading", max_length=255
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Optional subheading text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Call to action button text",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Call to action button URL",
                                        required=False,
                                    ),
                                ),
                                (
                                    "background_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Background image for the hero section",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "features",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="Section heading",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.TextBlock(
                                        help_text="Optional section subheading",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "features",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Icon class or name (e.g., 'rocket', 'star')",
                                                        max_length=50,
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Feature title",
                                                        max_length=100,
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        help_text="Feature description"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Add 2-6 features",
                                        max_num=6,
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "statistics",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="Our Impact",
                                        help_text="Section heading",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "metrics",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "value",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Metric value (e.g., 150+, 98%, 24h)",
                                                        max_length=20,
                                                    ),
                                                ),
                                                (
                                                    "label",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="Metric label (e.g., Projects Completed)",
                                                        max_length=100,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        help_text="Add 2-6 metrics",
                                        max_num=6,
                                        min_num=2,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "testimonial",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="Customer testimonial quote"
                                    ),
                                ),
                                (
                                    "author_name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Author name", max_length=100
                                    ),
                                ),
                                (
                                    "author_title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Author job title",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "company",
                                    wagtail.blocks.CharBlock(
                                        help_text="Company name",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                                (
                                    "author_image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Author photo", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        help_text="CTA heading", max_length=255
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Supporting text",
                                        max_length=500,
                                        required=False,
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        help_text="Button text", max_length=100
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.URLBlock(help_text="Button URL"),
                                ),
                                (
                                    "background_color",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("primary", "Primary"),
                                            ("secondary", "Secondary"),
                                            ("dark", "Dark"),
                                            ("light", "Light"),
                                        ],
                                        help_text="Background color theme",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "h2",
                                            "h3",
                                            "h4",
                                            "bold",
                                            "italic",
                                            "link",
                                            "ol",
                                            "ul",
                                            "document-link",
                                            "image",
                                            "embed",
                                        ],
                                        help_text="Rich text content",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Select an image"
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.CharBlock(
                                        help_text="Optional image caption",
                                        max_length=255,
                                        required=False,
                                    ),
                                ),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("center", "Center"),
                                            ("right", "Right"),
                                        ],
                                        help_text="Image alignment",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Main hero heading",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Optional subheading text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Call to action button text",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Call to action button URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Background image for the hero section",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "features",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Optional section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "features",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "icon",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Icon class or name (e.g., 'rocket', 'star')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Feature title",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Feature description"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add 2-6 features",
                                                max_num=6,
                                                min_num=2,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "testimonial",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "quote",
                                            wagtail.blocks.TextBlock(
                                                help_text="Customer testimonial quote"
                                            ),
                                        ),
                                        (
                                            "author_name",
                                            wagtail.blocks.CharBlock(
                                                help_text="Author name", max_length=100
                                            ),
                                        ),
                                        (
                                            "author_title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Author job title",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "company",
                                            wagtail.blocks.CharBlock(
                                                help_text="Company name",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "author_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Author photo", required=False
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="CTA heading", max_length=255
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.TextBlock(
                                                help_text="Supporting text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "button_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Button text", max_length=100
                                            ),
                                        ),
                                        (
                                            "button_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Button URL"
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("primary", "Primary"),
                                                    ("secondary", "Secondary"),
                                                    ("dark", "Dark"),
                                                    ("light", "Light"),
                                                ],
                                                help_text="Background color theme",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "ol",
                                                    "ul",
                                                    "document-link",
                                                    "image",
                                                    "embed",
                                                ],
                                                help_text="Rich text content",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Select an image"
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional image caption",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ],
                                                help_text="Image alignment",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open Graph image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="PortfolioPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Main hero heading",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Optional subheading text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Call to action button text",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Call to action button URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Background image for the hero section",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "statistics",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Our Impact",
                                                help_text="Section heading",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "metrics",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "value",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Metric value (e.g., 150+, 98%, 24h)",
                                                                max_length=20,
                                                            ),
                                                        ),
                                                        (
                                                            "label",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Metric label (e.g., Projects Completed)",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add 2-6 metrics",
                                                max_num=6,
                                                min_num=2,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "portfolio_projects",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Our Portfolio",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "projects",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Project title",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Project description",
                                                                max_length=500,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.RawHTMLBlock(
                                                                help_text="SVG icon HTML code"
                                                            ),
                                                        ),
                                                        (
                                                            "tags",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.CharBlock(
                                                                    max_length=50
                                                                ),
                                                                help_text="Project tags",
                                                                max_num=8,
                                                                min_num=1,
                                                            ),
                                                        ),
                                                        (
                                                            "package",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Package type (e.g., 'Starter', 'Pro', 'Elite')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "timeline",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Project timeline (e.g., '2 weeks', '4-6 weeks')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "category",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Project category (e.g., 'SaaS', 'E-Commerce')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                help_text="Project image",
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "technologies",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.CharBlock(
                                                                    max_length=50
                                                                ),
                                                                help_text="Technologies used",
                                                                max_num=10,
                                                                min_num=1,
                                                            ),
                                                        ),
                                                        (
                                                            "status",
                                                            wagtail.blocks.ChoiceBlock(
                                                                choices=[
                                                                    (
                                                                        "completed",
                                                                        "Completed",
                                                                    ),
                                                                    (
                                                                        "in-progress",
                                                                        "In Progress",
                                                                    ),
                                                                    (
                                                                        "featured",
                                                                        "Featured",
                                                                    ),
                                                                ],
                                                                help_text="Project status",
                                                            ),
                                                        ),
                                                        (
                                                            "visits",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Visits metric (e.g., '10K+')",
                                                                max_length=50,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "conversion",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Conversion metric (e.g., '25%')",
                                                                max_length=50,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "performance",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Performance metric (e.g., '98%')",
                                                                max_length=50,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add portfolio projects",
                                                max_num=20,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "case_studies",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Success Stories",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "case_studies",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Case study title",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "business",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Business name",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.RawHTMLBlock(
                                                                help_text="SVG icon HTML code"
                                                            ),
                                                        ),
                                                        (
                                                            "metric1_value",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="First metric value",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "metric1_label",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="First metric label",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "metric2_value",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Second metric value",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "metric2_label",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Second metric label",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Case study description",
                                                                max_length=1000,
                                                            ),
                                                        ),
                                                        (
                                                            "package",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Package used",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "timeline",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Project timeline",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "testimonial",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Client testimonial",
                                                                max_length=500,
                                                                required=False,
                                                            ),
                                                        ),
                                                        (
                                                            "client",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Client name",
                                                                max_length=100,
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add case studies",
                                                max_num=10,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "technologies",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Technologies We Use",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "technologies",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "name",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Technology name",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.RawHTMLBlock(
                                                                help_text="SVG icon HTML code"
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add technologies",
                                                max_num=20,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="CTA heading", max_length=255
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.TextBlock(
                                                help_text="Supporting text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "button_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Button text", max_length=100
                                            ),
                                        ),
                                        (
                                            "button_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Button URL"
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("primary", "Primary"),
                                                    ("secondary", "Secondary"),
                                                    ("dark", "Dark"),
                                                    ("light", "Light"),
                                                ],
                                                help_text="Background color theme",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "ol",
                                                    "ul",
                                                    "document-link",
                                                    "image",
                                                    "embed",
                                                ],
                                                help_text="Rich text content",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Select an image"
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional image caption",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ],
                                                help_text="Image alignment",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open Graph image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="ServicesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            (
                                "hero",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="Main hero heading",
                                                max_length=255,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Optional subheading text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Call to action button text",
                                                max_length=100,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "cta_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Call to action button URL",
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "background_image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Background image for the hero section",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "service_packages",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Choose Your Perfect Package",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "packages",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Package title",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Package description",
                                                                max_length=500,
                                                            ),
                                                        ),
                                                        (
                                                            "price",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Price (e.g., 'From $2,500')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "duration",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Duration (e.g., '2 weeks')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.RawHTMLBlock(
                                                                help_text="SVG icon HTML code"
                                                            ),
                                                        ),
                                                        (
                                                            "features",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.CharBlock(
                                                                    max_length=200
                                                                ),
                                                                help_text="Package features",
                                                                max_num=10,
                                                                min_num=1,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add service packages",
                                                max_num=5,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "ala_carte_services",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="A La Carte Services",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "services",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Service title",
                                                                max_length=100,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="Service description",
                                                                max_length=300,
                                                            ),
                                                        ),
                                                        (
                                                            "price",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Price (e.g., '$350')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.RawHTMLBlock(
                                                                help_text="SVG icon HTML code"
                                                            ),
                                                        ),
                                                        (
                                                            "category",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Service category (e.g., 'Design', 'Development')",
                                                                max_length=50,
                                                            ),
                                                        ),
                                                        (
                                                            "features",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.CharBlock(
                                                                    max_length=200
                                                                ),
                                                                help_text="Service features",
                                                                max_num=8,
                                                                min_num=1,
                                                            ),
                                                        ),
                                                        (
                                                            "popular",
                                                            wagtail.blocks.BooleanBlock(
                                                                help_text="Mark as popular service",
                                                                required=False,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add a la carte services",
                                                max_num=20,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "faq_section",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                default="Frequently Asked Questions",
                                                help_text="Section heading",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "subheading",
                                            wagtail.blocks.TextBlock(
                                                help_text="Section subheading",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "faqs",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "question",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="FAQ question",
                                                                max_length=200,
                                                            ),
                                                        ),
                                                        (
                                                            "answer",
                                                            wagtail.blocks.TextBlock(
                                                                help_text="FAQ answer",
                                                                max_length=1000,
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                help_text="Add FAQ items",
                                                max_num=15,
                                                min_num=1,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "cta",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                help_text="CTA heading", max_length=255
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.TextBlock(
                                                help_text="Supporting text",
                                                max_length=500,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "button_text",
                                            wagtail.blocks.CharBlock(
                                                help_text="Button text", max_length=100
                                            ),
                                        ),
                                        (
                                            "button_link",
                                            wagtail.blocks.URLBlock(
                                                help_text="Button URL"
                                            ),
                                        ),
                                        (
                                            "background_color",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("primary", "Primary"),
                                                    ("secondary", "Secondary"),
                                                    ("dark", "Dark"),
                                                    ("light", "Light"),
                                                ],
                                                help_text="Background color theme",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "text",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "content",
                                            wagtail.blocks.RichTextBlock(
                                                features=[
                                                    "h2",
                                                    "h3",
                                                    "h4",
                                                    "bold",
                                                    "italic",
                                                    "link",
                                                    "ol",
                                                    "ul",
                                                    "document-link",
                                                    "image",
                                                    "embed",
                                                ],
                                                help_text="Rich text content",
                                            ),
                                        )
                                    ]
                                ),
                            ),
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Select an image"
                                            ),
                                        ),
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(
                                                help_text="Optional image caption",
                                                max_length=255,
                                                required=False,
                                            ),
                                        ),
                                        (
                                            "alignment",
                                            wagtail.blocks.ChoiceBlock(
                                                choices=[
                                                    ("left", "Left"),
                                                    ("center", "Center"),
                                                    ("right", "Right"),
                                                ],
                                                help_text="Image alignment",
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        blank=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open Graph image for social media sharing",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Services Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
