# Generated by Django 5.0.2 on 2025-09-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("WAGTAIL_NAVBAR", "Wagtail Managed Navbar"),
                            ("WAGTAIL_FOOTER", "Wagtail Managed Footer"),
                            ("WAGTAIL_LAYOUT", "Wagtail Layout System"),
                            ("WAGTAIL_HERO", "Wagtail Hero Sections"),
                            ("WAGTAIL_FEATURES", "Wagtail Feature Grids"),
                            ("WAGTAIL_TESTIMONIALS", "Wagtail Testimonials"),
                            ("WAGTAIL_CTA", "Wagtail CTA Sections"),
                            ("WAGTAIL_BLOG", "Wagtail Blog System"),
                            ("WAGTAIL_PORTFOLIO", "Wagtail Portfolio System"),
                            ("WAGTAIL_SERVICES", "Wagtail Services Pages"),
                            ("WAGTAIL_CONTACT_FORM", "Wagtail Contact Forms"),
                            ("WAGTAIL_NEWSLETTER", "Wagtail Newsletter Signup"),
                            ("WAGTAIL_ANIMATIONS", "Wagtail Animation System"),
                            ("WAGTAIL_PARTICLES", "Wagtail Particle Effects"),
                            ("WAGTAIL_SEO", "Wagtail SEO Management"),
                            ("WAGTAIL_META", "Wagtail Meta Tags"),
                            ("WAGTAIL_LAZY_LOADING", "Wagtail Lazy Loading"),
                            ("WAGTAIL_CACHING", "Wagtail Caching System"),
                            ("WAGTAIL_AI_CONTENT", "Wagtail AI Content Generation"),
                            ("WAGTAIL_ANALYTICS", "Wagtail Analytics Integration"),
                        ],
                        help_text="Feature flag name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable feature name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this feature does",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NAVIGATION", "Navigation & Layout"),
                            ("CONTENT", "Content Management"),
                            ("FORMS", "Forms & Interactions"),
                            ("ANIMATIONS", "Animations & Effects"),
                            ("SEO", "SEO & Meta"),
                            ("PERFORMANCE", "Performance & Optimization"),
                            ("EXPERIMENTAL", "Experimental Features"),
                        ],
                        default="CONTENT",
                        help_text="Feature category for organization",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feature is currently enabled",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("ALL", "All Environments"),
                            ("DEVELOPMENT", "Development Only"),
                            ("STAGING", "Staging Only"),
                            ("PRODUCTION", "Production Only"),
                        ],
                        default="ALL",
                        help_text="Environment where this feature should be active",
                        max_length=20,
                    ),
                ),
                (
                    "rollout_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Percentage of users who should see this feature (0-100)",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to start showing this feature",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing this feature (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as deprecated when replacing with Wagtail version",
                    ),
                ),
                (
                    "deprecation_notes",
                    models.TextField(
                        blank=True, help_text="Notes about deprecation and migration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other features that must be enabled for this to work",
                        to="core.featureflag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "ordering": ["category", "name"],
            },
        ),
    ]
