# Generated by Django 5.0.2 on 2025-08-13 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Contact name", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email address", max_length=254
                    ),
                ),
                ("message", models.TextField(help_text="Contact message/inquiry")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website Contact Form"),
                            ("landing_page", "Landing Page"),
                            ("newsletter", "Newsletter Signup"),
                            ("demo_request", "Demo Request"),
                            ("other", "Other"),
                        ],
                        default="website",
                        help_text="Source of the lead",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the lead was submitted",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the submitter", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Has this lead been processed?"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the lead was processed", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="leads_lead_created_302c6d_idx"
                    ),
                    models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
                    models.Index(
                        fields=["source"], name="leads_lead_source_200868_idx"
                    ),
                    models.Index(
                        fields=["is_processed"], name="leads_lead_is_proc_a8a4df_idx"
                    ),
                ],
            },
        ),
    ]
