name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build application
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}
          VITE_APP_DESCRIPTION: ${{ secrets.VITE_APP_DESCRIPTION }}
          VITE_FORMSPREE_ENDPOINT: ${{ secrets.VITE_FORMSPREE_ENDPOINT }}
          VITE_ENABLE_ANALYTICS: ${{ secrets.VITE_ENABLE_ANALYTICS }}
          VITE_ENABLE_ERROR_REPORTING: ${{ secrets.VITE_ENABLE_ERROR_REPORTING }}
          # Feature flags
          VITE_BLOG_PAGES: ${{ secrets.VITE_BLOG_PAGES }}
          VITE_ROCKET_ANIMATION: ${{ secrets.VITE_ROCKET_ANIMATION }}
          VITE_WAGTAIL_NAVBAR: ${{ secrets.VITE_WAGTAIL_NAVBAR }}
          VITE_WAGTAIL_FOOTER: ${{ secrets.VITE_WAGTAIL_FOOTER }}
          VITE_WAGTAIL_LAYOUT: ${{ secrets.VITE_WAGTAIL_LAYOUT }}
          VITE_WAGTAIL_HERO: ${{ secrets.VITE_WAGTAIL_HERO }}
          VITE_WAGTAIL_FEATURES: ${{ secrets.VITE_WAGTAIL_FEATURES }}
          VITE_WAGTAIL_TESTIMONIALS: ${{ secrets.VITE_WAGTAIL_TESTIMONIALS }}
          VITE_WAGTAIL_CTA: ${{ secrets.VITE_WAGTAIL_CTA }}
          VITE_WAGTAIL_BLOG: ${{ secrets.VITE_WAGTAIL_BLOG }}
          VITE_WAGTAIL_PORTFOLIO: ${{ secrets.VITE_WAGTAIL_PORTFOLIO }}
          VITE_WAGTAIL_SERVICES: ${{ secrets.VITE_WAGTAIL_SERVICES }}
          VITE_WAGTAIL_CONTACT_FORM: ${{ secrets.VITE_WAGTAIL_CONTACT_FORM }}
          VITE_WAGTAIL_NEWSLETTER: ${{ secrets.VITE_WAGTAIL_NEWSLETTER }}
          VITE_WAGTAIL_SEO: ${{ secrets.VITE_WAGTAIL_SEO }}
          VITE_WAGTAIL_META: ${{ secrets.VITE_WAGTAIL_META }}
          VITE_WAGTAIL_ANIMATIONS: ${{ secrets.VITE_WAGTAIL_ANIMATIONS }}
          VITE_WAGTAIL_PARTICLES: ${{ secrets.VITE_WAGTAIL_PARTICLES }}
          VITE_WAGTAIL_LAZY_LOADING: ${{ secrets.VITE_WAGTAIL_LAZY_LOADING }}
          VITE_WAGTAIL_CACHING: ${{ secrets.VITE_WAGTAIL_CACHING }}
          VITE_WAGTAIL_AI_CONTENT: ${{ secrets.VITE_WAGTAIL_AI_CONTENT }}
          VITE_WAGTAIL_ANALYTICS: ${{ secrets.VITE_WAGTAIL_ANALYTICS }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          output_location: "dist"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
